### ISSUE TITLE
Kubernetes version?

### ISSUE THREAD

**Issue by sokoow** [codius/codiusd#29]
Why hyperd when we have kubernetes ruling the world ? Will you provide a kube version of this ever ?

**Comment by sharafian** [comment]
hyperd uses hardware virtualization to make it safe to run pods in a multi-tenant environment. As far as I know, kubernetes doesn't come with that feature, so we would have to write it ourselves.

**Comment by sokoow** [comment]
Fair point but you're exaggerating a bit :) I don't think you have to implement anything on top of kube bar interledger deployment process for it. My point here is that if you create kube based pipeline, statistically you've way more chance to get attention/commiters to your project - skip the part of hardware isolation, kube community it's huge. Hyperd looks like a very niche platform that has uncertain future still.

**Comment by spearl** [comment]
Unfortunately you can't skip hardware isolation for this use case.
We're running containers on external hosts. Containers alone (and k8s as well) provide basically no security guarantees. The hosted code must be sandboxed or it can easily disrupt other guest containers or the host itself.
This is not to say we won't try to build in k8s compatibility in the future or support more exotic isolation methods. But for now hyper works since it fits our niche use case.
